package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Eventhasinterests generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "eventhasinterests", catalog = "bd_planizator")
public class EventHasInterests implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEventHasInterests", unique = true, nullable = false)
	private int idEventHasInterests;
	@ManyToOne
	@JoinColumn(name = "idEvent", nullable = false)
	private Event event;
	@ManyToOne
	@JoinColumn(name = "idInterest", nullable = false)
	private Interest interest;

	public EventHasInterests() {
	}

	public EventHasInterests(int idEventHasInterests, Event event, Interest interest) {
		this.idEventHasInterests = idEventHasInterests;
		this.event = event;
		this.interest = interest;
	}

	public int getIdEventHasInterests() {
		return this.idEventHasInterests;
	}

	public void setIdEventHasInterests(int idEventHasInterests) {
		this.idEventHasInterests = idEventHasInterests;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

}
