package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "event", catalog = "bd_planizator")
public class Event implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEvent", unique = true, nullable = false)
	private Integer idEvent;
	@ManyToOne
	@JoinColumn(name = "createdBy_idUser")
	private User user;
	@Column(name = "title", nullable = false, length = 60)
	private String title;
	@Column(name = "description", nullable = false, length = 65535)
	private String description;
	@Column(name = "location", length = 45)
	private String location;
	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 0)
	private Date date;
	@Column(name = "photo")
	private byte[] photo;
	@Column(name = "ageLimitUpTo")
	private Byte ageLimitUpTo;
	@Column(name = "ageLimitDownTo")
	private Byte ageLimitDownTo;
	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 0)
	private Date dateCreated;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "event")
	private Set<UserHasEvents> userhaseventses = new HashSet<UserHasEvents>(0);
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "event")
	private Set<EventHasInterests> eventhasinterestses = new HashSet<EventHasInterests>(0);

	public Event() {
	}

	public Event(String title, String description) {
		this.title = title;
		this.description = description;
	}

	public Event(User user, String title, String description, String location, Date date, byte[] photo,
			Byte ageLimitUpTo, Byte ageLimitDownTo, Date dateCreated, Set<UserHasEvents> userhaseventses,
			Set<EventHasInterests> eventhasinterestses) {
		this.user = user;
		this.title = title;
		this.description = description;
		this.location = location;
		this.date = date;
		this.photo = photo;
		this.ageLimitUpTo = ageLimitUpTo;
		this.ageLimitDownTo = ageLimitDownTo;
		this.dateCreated = dateCreated;
		this.userhaseventses = userhaseventses;
		this.eventhasinterestses = eventhasinterestses;
	}




	public Integer getIdEvent() {
		return this.idEvent;
	}

	public void setIdEvent(Integer idEvent) {
		this.idEvent = idEvent;
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}


	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}


	public Byte getAgeLimitUpTo() {
		return this.ageLimitUpTo;
	}

	public void setAgeLimitUpTo(Byte ageLimitUpTo) {
		this.ageLimitUpTo = ageLimitUpTo;
	}


	public Byte getAgeLimitDownTo() {
		return this.ageLimitDownTo;
	}

	public void setAgeLimitDownTo(Byte ageLimitDownTo) {
		this.ageLimitDownTo = ageLimitDownTo;
	}


	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Set<UserHasEvents> getUserhaseventses() {
		return this.userhaseventses;
	}

	public void setUserhaseventses(Set<UserHasEvents> userhaseventses) {
		this.userhaseventses = userhaseventses;
	}


	public Set<EventHasInterests> getEventhasinterestses() {
		return this.eventhasinterestses;
	}

	public void setEventhasinterestses(Set<EventHasInterests> eventhasinterestses) {
		this.eventhasinterestses = eventhasinterestses;
	}

}
