package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Interest generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "interest", catalog = "bd_planizator")
public class Interest implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idInterest", unique = true, nullable = false)
	private int idInterest;
	@Column(name = "name", nullable = false, length = 45)
	private String name;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "interest")
	private Set<UsersHasInterests> usershasinterestses = new HashSet<UsersHasInterests>(0);
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "interest")
	private Set<EventHasInterests> eventhasinterestses = new HashSet<EventHasInterests>(0);

	public Interest() {
	}

	public Interest(int idInterest, String name) {
		this.idInterest = idInterest;
		this.name = name;
	}

	public Interest(int idInterest, String name, Set<UsersHasInterests> usershasinterestses,
			Set<EventHasInterests> eventhasinterestses) {
		this.idInterest = idInterest;
		this.name = name;
		this.usershasinterestses = usershasinterestses;
		this.eventhasinterestses = eventhasinterestses;
	}


	public int getIdInterest() {
		return this.idInterest;
	}

	public void setIdInterest(int idInterest) {
		this.idInterest = idInterest;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Set<UsersHasInterests> getUsershasinterestses() {
		return this.usershasinterestses;
	}

	public void setUsershasinterestses(Set<UsersHasInterests> usershasinterestses) {
		this.usershasinterestses = usershasinterestses;
	}


	public Set<EventHasInterests> getEventhasinterestses() {
		return this.eventhasinterestses;
	}

	public void setEventhasinterestses(Set<EventHasInterests> eventhasinterestses) {
		this.eventhasinterestses = eventhasinterestses;
	}

}
