package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usershasinterests generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "usershasinterests", catalog = "bd_planizator")
public class UsersHasInterests implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUsersHasInterests", unique = true, nullable = false)
	private int idUsersHasInterests;
	@ManyToOne
	@JoinColumn(name = "idInterest", nullable = false)
	private Interest interest;
	@ManyToOne
	@JoinColumn(name = "idUser", nullable = false)
	private User user;

	public UsersHasInterests() {
	}

	public UsersHasInterests(int idUsersHasInterests, Interest interest, User user) {
		this.idUsersHasInterests = idUsersHasInterests;
		this.interest = interest;
		this.user = user;
	}

	public int getIdUsersHasInterests() {
		return this.idUsersHasInterests;
	}

	public void setIdUsersHasInterests(int idUsersHasInterests) {
		this.idUsersHasInterests = idUsersHasInterests;
	}

	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
