package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userhasevents generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "userhasevents", catalog = "bd_planizator")
public class UserHasEvents implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUserHasEvents", unique = true, nullable = false)
	private Integer idUserHasEvents;
	@ManyToOne
	@JoinColumn(name = "idEvent", nullable = false)
	private Event event;
	@ManyToOne
	@JoinColumn(name = "idUser", nullable = false)
	private User user;
	@Temporal(TemporalType.DATE)
	@Column(name = "dateJoined", nullable = false, length = 0)
	private Date dateJoined;

	public UserHasEvents() {
	}

	public UserHasEvents(Event event, User user, Date dateJoined) {
		this.event = event;
		this.user = user;
		this.dateJoined = dateJoined;
	}

	public Integer getIdUserHasEvents() {
		return this.idUserHasEvents;
	}

	public void setIdUserHasEvents(Integer idUserHasEvents) {
		this.idUserHasEvents = idUserHasEvents;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateJoined() {
		return this.dateJoined;
	}

	public void setDateJoined(Date dateJoined) {
		this.dateJoined = dateJoined;
	}

}
