package es.josemaria.aparicio.bean;
// default package
// Generated 27-mar-2017 20:38:40 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userhasmessages generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "userhasmessages", catalog = "bd_planizator")
public class UserHasMessages implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUserHasMessages", unique = true, nullable = false)
	private int idUserHasMessages;
	@ManyToOne
	@JoinColumn(name = "idMessage", nullable = false)
	private Message message;
	@ManyToOne
	@JoinColumn(name = "SendedTo_idUser", nullable = false)
	private User user;

	public UserHasMessages() {
	}

	public UserHasMessages(int idUserHasMessages, Message message, User user) {
		this.idUserHasMessages = idUserHasMessages;
		this.message = message;
		this.user = user;
	}

	public int getIdUserHasMessages() {
		return this.idUserHasMessages;
	}

	public void setIdUserHasMessages(int idUserHasMessages) {
		this.idUserHasMessages = idUserHasMessages;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
